default:
  image: epigenesys/rails:ruby2.6.5

  services:
    - postgres:latest

  before_script:
    - yarn install --production --pure-lockfile --cache-folder .yarn-cache
    - 'bundle config gems.shefcompsci.org.uk gitlab:${GEM_SERVER_KEY}'
    - bundle check --path vendor || bundle install --path vendor -j $(nproc)

.db-setup: &db-setup |
  cat > config/database.yml << EOF
  test:
    adapter:  postgresql
    host:     postgres
    database: $POSTGRES_DB
    username: $POSTGRES_USER
    password: $POSTGRES_PASSWORD
  EOF

.default-cache: &default-cache
  key:
    files:
      - Gemfile.lock
      - package.json
  paths:
    - vendor/ruby
    - node_modules
    - .yarn-cache/

.pull-cache: &pull-cache
  cache:
    <<: *default-cache
    policy: pull

stages:
  - prepare
  - test
  - post-test

variables:
  POSTGRES_DB: ci_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: password

setup-test-env:
  stage: prepare
  cache:
    <<: *default-cache
  script:
    - *db-setup
    - bundle exec rails db:drop db:create db:schema:load RAILS_ENV=test
  artifacts:
    expire_in: 1d
    paths:
      - config/database.yml

.rspec:
  stage: test
  <<: *pull-cache
  dependencies: ['setup-test-env']
  needs: ['setup-test-env']
  script:
    - bundle exec rspec ${CI_JOB_NAME//[:]/\/}
  artifacts:
    paths:
      - 'coverage/$CI_JOB_NAME'
    when: always
    expire_in: 1h

spec:helpers spec:mailers spec:policies spec:validators:
  extends: .rspec

spec:models:
  extends: .rspec

spec:requests:
  extends: .rspec

#spec/system:
#  extends: .rspec
#  before_script:
#    - bundle exec rails runner -e test 'Webdrivers.install_dir = Rails.root.join("vendor", "webdrivers"); Webdrivers::Chromedriver.update'

coverage:
  stage: post-test
  when: always
  <<: *pull-cache
  script:
    - bundle exec ruby lib/scripts/merge-simplecov.rb
    - source lib/scripts/push-coverage-report.sh
  coverage: '/LOC \((\d+\.\d+%)\) covered.$/'
